### ISSUE TITLE
Suggestion for STATION_NUMBER parameter to gather stations that contain specified text

### ISSUE THREAD

**Issue by jongoetz** [bcgov/tidyhydat#7]
For the STATION_NUMBER parameter in the functions, I suggest having it have the ability to look up stations that contain text, not just matching text (other than "ALL"). For example, one can type in just “08NM” and pulls all data from all stations containing 08NM in the number.

**Comment by boshek** [comment]
I think that partial matching is probably not the right approach to build directly into each function. I think it introduces some ambiguity directly into the function. Rather I've create a `search_number` function here: https://github.com/bcgov/tidyhydat/commit/b2849ec57304ef17416ab9f310e09c5a18a9692b. 

Using this function we can partially match as described above:
`search_number("08HF")`

This could even be supplied directly to a function like `DLY_FLOWS`:
`DLY_FLOWS(STATION_NUMBER = search_number("08HF")$STATION_NUMBER)`
